import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { FireBaseProvider } from "@/context/firebaseContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import HeaderLayout from "@/components/HeaderLayout";
import { EMIContextProvider } from "@/context/EMIContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900", 
// });

export const metadata: Metadata = {
  title: "Car Financing App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>

      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="h-screen bg-white text-black"
        id="documentBody"
      >
        <FireBaseProvider>
          <EMIContextProvider>
            <ToastContainer />
            <HeaderLayout>{children}</HeaderLayout>
          </EMIContextProvider>
        </FireBaseProvider>
      </body>
    </html>
  );
}
